name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: abstract.tex
      - name: Setup deploy folder
        run: |
          mkdir ghpages
          mv abstract.pdf ghpages/moore-haitjema-alizadehsaravi-icsc-2024.pdf
      - name: Push PDF to ghpages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ghpages
          single-commit: true
